name: localization_by_muz
description: A simple Flutter package for easy JSON-based localization with parameter interpolation and instant language switching
version: 2.0.0

homepage: https://github.com/muzzammil763/localization_by_muz
repository: https://github.com/muzzammil763/localization_by_muz
issue_tracker: https://github.com/muzzammil763/localization_by_muz/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any